# Generated by Django 2.2.9 on 2020-07-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=200, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Disponible'), (1, 'Reservado'), (2, 'Ocupado')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('autor_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='inicio.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_libro', to='inicio.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prestamista', models.CharField(max_length=200, unique=True)),
                ('telefono', models.CharField(max_length=8)),
                ('no_identificacion', models.IntegerField(null=True)),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('notas', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('libros', models.ManyToManyField(related_name='libros', to='inicio.Libro')),
            ],
        ),
    ]
