# Generated by Django 2.2.9 on 2020-08-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='libros',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='libro_prestado', to='inicio.Libro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='no_identificacion',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_identificacion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='identificacion', to='inicio.Identificacion'),
            preserve_default=False,
        ),
    ]
