# Generated by Django 2.2.9 on 2020-10-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20200808_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('intitucion', models.CharField(max_length=80)),
                ('numero_contacto', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
