# Generated by Django 2.2.9 on 2020-10-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_donativos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donativos',
            new_name='Donativo',
        ),
    ]
