# Generated by Django 2.2.9 on 2020-10-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20201017_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donativo',
            old_name='intitucion',
            new_name='institucion',
        ),
    ]
