# Generated by Django 2.2.9 on 2020-10-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20201017_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'Reservado'), (2, 'Ocupado')], default=1),
        ),
    ]
