# Generated by Django 2.2.9 on 2020-10-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20201024_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='nombre_prestamista',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
