# Generated by Django 2.2.9 on 2020-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20201024_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'Reservado'), (2, 'Ocupado')], default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
