# Generated by Django 2.2.9 on 2020-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20201027_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='donativo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
