# Generated by Django 2.2.9 on 2020-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_auto_20201027_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donativo',
            name='archivo',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
