# Generated by Django 2.2.9 on 2020-10-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_auto_20201027_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donativo',
            name='archivo',
        ),
    ]
